using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Net.Mail;
using System.Net.Mime;

namespace MarkIt.login_register
{
    /// <summary>
    /// Interaction logic for PageRecetPassword1.xaml
    /// </summary>
    public partial class PageRecetPassword1 : Page
    {
        public static int code {  get; private set; }
        public static string email {  get; private set; }
        public PageRecetPassword1()
        {
            InitializeComponent();
        }

        private async void ButtonSend_Click(object sender, RoutedEventArgs e)
        {
            email = TextBoxEmail.Text;
            ClassUserList? userList = await UserManager.GetUsersFromServerAndHandleErrors(LoadingScreen);
            if(userList == null)
            {
                return;
            }
            bool exists = false;
            foreach(ClassUser user in userList.Users)
            {
                if (user.Email == email) { exists = true; break; }
            }
            if (!exists)
            {
                MessageBox.Show("This user does not exist. Enter an existing user or create an account!", "No user", MessageBoxButton.OK, MessageBoxImage.Question);
                return;
            }
            if (SendEmail(email, "password reset"))
            {
                WindowUserLogin.Navigate("PagePassword1", "PagePassword2");
                PageRecetPassword2.Timer.Start();
            }
            else
            {
                MessageBox.Show("Failed to send email. Please try again!", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                Logger.logger.Fatal("Failed to send email.");
            }
        }

        private void ButtonCancel_Click(object sender, RoutedEventArgs e)
        {
            WindowUserLogin.Navigate("PagePassword1", "PageLogin");
        }

        static public bool SendEmail(string emailAddress, string reason)
        {
            try
            {
                code = new Random().Next(0, 1000000);
                // Code from StackOverFlow
                // search: C# email senden, how to
                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);

                client.UseDefaultCredentials = false;
                client.EnableSsl = true;
                // this is only a fake email, we delete it after the project is finished
                System.Net.NetworkCredential basicauth = new System.Net.NetworkCredential("markit.app.noreply@gmail.com", "kipy tubr chhv qyef");
                client.Credentials = basicauth;
                MailAddress from = new MailAddress("markit.app.noreply@gmail.comm", "MarkIt");
                MailAddress to;
                try
                {
                    to = new MailAddress(emailAddress, "");
                }
                catch
                {
                    Logger.logger.Warning($"Mailaddress {emailAddress} not correct format.");
                    throw new Exception("mailaddress");
                }
                MailMessage mail = new MailMessage(from, to);
                mail.SubjectEncoding = Encoding.UTF8;
                if(reason == "password reset")
                {
                    mail.Subject = "MarkIt Password-Reset";
                    // html code generated by ChatGPT
                    mail.Body = $"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Password Reset</title></head><body style='font-family:Arial,sans-serif;background-color:#f4f4f4;padding:20px;'><table width='100%' cellspacing='0' cellpadding='0'><tr><td align='center'><table width='500' style='background-color:#ffffff;padding:30px;border-radius:10px;'><tr><td align='center'><h2>Password Reset</h2></td></tr><tr><td><p>Hello,</p><p>You requested to reset your password.</p><p>Please use the following verification code:</p></td></tr><tr><td align='center' style='padding:20px;'><div style='font-size:28px;font-weight:bold;letter-spacing:5px;'>{code:D6}</div></td></tr><tr><td><p>This code is valid for a limited time.</p><p>If you did not request this, you can safely ignore this email.</p></td></tr><tr><td style='padding-top:20px;font-size:12px;color:#777;'><p>This is an automated message. Please do not reply.</p></td></tr></table></td></tr></table></body></html>";
                }
                else if(reason == "2fa")
                {
                    mail.Subject = "MarkIt Email-Verification";
                    // html code generated by ChatGPT
                    mail.Body = $"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Email Verification</title></head><body style='font-family:Arial,sans-serif;background-color:#f4f4f4;padding:20px;'><table width='100%' cellspacing='0' cellpadding='0'><tr><td align='center'><table width='500' style='background-color:#ffffff;padding:30px;border-radius:10px;'><tr><td align='center'><h2>Email Verification</h2></td></tr><tr><td><p>Hello,</p><p>Please verify your email address.</p><p>Use the following verification code:</p></td></tr><tr><td align='center' style='padding:20px;'><div style='font-size:28px;font-weight:bold;letter-spacing:5px;'>{code:D6}</div></td></tr><tr><td><p>This code is valid for a limited time.</p><p>If you did not create an account, you can safely ignore this email.</p></td></tr><tr><td style='padding-top:20px;font-size:12px;color:#777;'><p>This is an automated message. Please do not reply.</p></td></tr></table></td></tr></table></body></html>";
                }
                else if (reason == "register")
                {
                    mail.Subject = "MarkIt-Register";
                    // html code generated by ChatGPT
                    mail.Body = $"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Email Verification</title></head><body style='font-family:Arial,sans-serif;background-color:#f4f4f4;padding:20px;'><table width='100%' cellspacing='0' cellpadding='0'><tr><td align='center'><table width='500' style='background-color:#ffffff;padding:30px;border-radius:10px;'><tr><td align='center'><h2>Email Verification</h2></td></tr><tr><td><p>Hello,</p><p>Please verify your email address.</p><p>Use the following verification code:</p></td></tr><tr><td align='center' style='padding:20px;'><div style='font-size:28px;font-weight:bold;letter-spacing:5px;'>{code:D6}</div></td></tr><tr><td><p>This code is valid for a limited time.</p><p>If you did not create an account, you can safely ignore this email.</p></td></tr><tr><td style='padding-top:20px;font-size:12px;color:#777;'><p>This is an automated message. Please do not reply.</p></td></tr></table></td></tr></table></body></html>";
                }
                mail.BodyEncoding = Encoding.UTF8;
                mail.IsBodyHtml = true;
                try
                {
                    client.Send(mail);
                    Logger.logger.Information($"Send email to \"{emailAddress}\" with code \"{code}\"");
                    return true;
                }
                catch
                {
                    Logger.logger.Fatal($"Sending E-Mail to {emailAddress}.");
                    throw new Exception("sending");
                }
            }
            catch (Exception e)
            {
                if (e.Message == "mailaddress")
                    MessageBox.Show("Something went wrong, check if your email address is in correct format and try again.", "Error",MessageBoxButton.OK, MessageBoxImage.Error);
                else if(e.Message == "sending")
                    MessageBox.Show("Something went wrong while sending the email, try again later.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                return false;
            }
        }
    }
}
