using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Navigation;
using static Org.BouncyCastle.Crypto.Engines.SM2Engine;

namespace MarkIt
{
    public class EmailManager
    {
        public int Code { get; private set; }
        public string Email { get; private set; }

        private enum ErrorType
        {
            OK,
            MailAddressFormat,
            Sending,
        };

        public EmailManager() { }

        public async Task<bool> SendEmailAndHandleErrors(string emailAddress, Grid loadingScreen)
        {
            loadingScreen.Visibility = Visibility.Visible;
            var (result, errortype) = await Task.Run(() =>
            {
                Code = new Random().Next(0, 1000000);
                // Code from StackOverFlow
                // search: C# email senden, how to
                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.UseDefaultCredentials = false;
                client.EnableSsl = true;
                // this is only a fake email, we delete it after the project is finished
                System.Net.NetworkCredential basicauth = new System.Net.NetworkCredential("markit.app.noreply@gmail.com", "kipy tubr chhv qyef");
                client.Credentials = basicauth;
                MailAddress from = new MailAddress("markit.app.noreply@gmail.comm", "MarkIt");
                MailAddress to;
                try
                {
                    to = new MailAddress(emailAddress, "");
                }
                catch
                {
                    Logger.logger.Warning($"Mailaddress {emailAddress} not correct format.");
                    return (false, ErrorType.MailAddressFormat);
                }
                MailMessage mail = new MailMessage(from, to);
                mail.SubjectEncoding = Encoding.UTF8;
                mail.Subject = "Verification Code";
                // html code generated by ChatGPT
                mail.Body = $"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Verification</title></head><body style='font-family:Arial,sans-serif;background-color:#f4f4f4;padding:20px;'><table width='100%' cellspacing='0' cellpadding='0'><tr><td align='center'><table width='500' style='background-color:#ffffff;padding:30px;border-radius:10px;'><tr><td align='center'><h2>Verification Code</h2></td></tr><tr><td><p>Hello,</p><p>You requested a verification code.</p><p>Please use the following code:</p></td></tr><tr><td align='center' style='padding:20px;'><div style='font-size:28px;font-weight:bold;letter-spacing:5px;'>{Code:D6}</div></td></tr><tr><td><p>This code is valid for a limited time.</p><p>If you did not request this, you can safely ignore this email.</p></td></tr><tr><td style='padding-top:20px;font-size:12px;color:#777;'><p>This is an automated message. Please do not reply.</p></td></tr></table></td></tr></table></body></html>";
                mail.BodyEncoding = Encoding.UTF8;
                mail.IsBodyHtml = true;
                try
                {
                    client.Send(mail);
                    Logger.logger.Information($"Send email to \"{emailAddress}\" with code \"{Code}\"");
                    return (true, ErrorType.OK);
                }
                catch
                {
                    Logger.logger.Fatal($"Sending E-Mail to {emailAddress}.");
                    return (false, ErrorType.Sending);
                }
            });
            loadingScreen.Visibility = Visibility.Hidden;
            if (result == false)
            {
                if (errortype == ErrorType.MailAddressFormat)
                {
                    MessageBox.Show("Something went wrong, check if your email address is in correct format and try again.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
                else if(errortype == ErrorType.Sending)
                {
                    MessageBox.Show("Something went wrong while sending the email, try again later.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
            return result;
        }
    }
}
